### ISSUE TITLE
User will be able to register a new account

### ISSUE THREAD

**Issue by wp57** [wp57/IT202007#1]
-ID (not shown on UI), Username, email, password (other fields optional)
- Password field should be 60 characters
-Passwords should be hashed (plain text passwords lose points)
-Email should be unique
-Username should be unique
-Form should have proper validations/checks for legitimate data
----Email validation
----Username validation (length/required)
----Password validation (length minimum)
----Confirm password match
-System should let user know if username or email is taken and allow the user to correct the error without wiping the form

**Comment by winonapatrick** [comment]
User can now register with username and pw

**Comment by wp57** [comment]
https://github.com/wp57/IT202007/commit/a0cd0e3d73f7e09dd2065bb5445213896525df67#diff-d8e7d8d77dfceff6cfbafa365f3751dc5ab6719f63908ad88fe7dddcec102af5
